plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  'ipfs-repo@*':
    dependencies:
      'it-drain': '*'
      'it-first': '*'
  'libp2p@*':
    dependencies:
      'abortable-iterator': '*'
  'libp2p-delegated-content-routing@*':
    dependencies:
      'peer-id': '*'
  'libp2p-gossipsub@*':
    peerDependencies:
      'libp2p': '*'
  'libp2p-utils@*':
    dependencies:
      'node-fetch': '*'
  'dns-over-http-resolver@*':
    dependencies:
      'node-fetch': '*'
