name: deploy
on:
  push:
    branches:
      - master
jobs:
  ghpage-publish:
    name: ghpage-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Set up dependency
        run: yarn install --frozen-lockfile
      - name: Build pages
        run: yarn build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/example/build
