name: deploy
on:
  push:
    branches:
      - master
jobs:
  ghpage-publish:
    name: ghpage-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Set up dependency
        run: yarn install --frozen-lockfile
      - name: Build pages
        run: yarn build
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/example/build
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Build distributions
        run: yarn
      - name: Publish to NPM
        uses: onichandame/github-action-npm-publish@v0.1.1
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # set this in github secrets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # leave as it is. auto generated
        with:
          packages: '@onichandame/react-ipfs-hook'
          mode: 'all'
          tag_package: '@onichandame/react-ipfs-hook'
